package com.gourav.weathersnap.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

// this entity represents a weather report that has been finalized and saved
@Entity(tableName = "saved_reports")
data class SavedReportEntity(
    // the id is auto generated by room when we insert a new report
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val cityName: String,
    val country: String,
    val latitude: Double,
    val longitude: Double,
    val temperatureCelsius: Double,
    val condition: String,
    val weatherCode: Int,
    val humidityPercent: Int,
    val windSpeedMetersPerSecond: Double,
    val pressureHPa: Double,
    val notes: String,
    // this stores the path to the compressed image on disk
    val imagePath: String,
    val originalSizeBytes: Long,
    val compressedSizeBytes: Long,
    // we use this timestamp to sort reports by date
    val savedAtMillis: Long,
)
